### ISSUE TITLE
Change App name

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/AniAirs#1]
Change the name of the application from `Animu` to `AniAirs` on the entire codebase.

**Comment by Amitkumarkoli** [comment]
can u please assign it to me, I am beginner in this.

**Comment by prerna12s** [comment]
@Abhigyan103 Please assign this issue to me under JWOC

**Comment by Abhigyan103** [comment]
Is there any update ?

**Comment by prerna12s** [comment]
yes ! I am just doing it .I 'll complete it by today

**Comment by Abhigyan103** [comment]
There are a lot of files that I have removed.. Please sync the code and then commit

**Comment by prerna12s** [comment]
ok
