### ISSUE TITLE
Implement Seasonal Calendar page

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/AniAirs#12]
**Is your feature request related to a problem? Please describe.**
The Seasonal Calendar is not implemented yet. Just implement it with basic functionalities.

**Describe the solution you'd like**
Just add the page which shows the seasonal animes and a dropdown to ask the season of which the animes have to be fetched (the seasons can also befetched, look in the jikanAPI documentation)

**Comment by YuvrajSingh3110** [comment]
Please assign this issue to me under JWOC
