### ISSUE TITLE
[UI/Figma] Improve the Card UI

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/AniAirs#13]
**Is your feature request related to a problem? Please describe.**
The Card UI is currently looking bland and need to be revamped.

**Describe the solution you'd like**
The new design should first be shown in Figma and then implemented.

**Describe alternatives you've considered**
If you just want to design in Figma and do not want to be bothered with the code, you can do that but the difficulty will be changed to `easy`.

**Comment by shashank-lol** [comment]
Pls assign this issue to me under JWOC

**Comment by shashank-lol** [comment]
![image](https://github.com/Abhigyan103/AniAirs/assets/115364171/d1c2dd8d-d3e6-4e57-9fe7-bb57b540a019)
Is this design fine?

**Comment by Abhigyan103** [comment]
Yes, Can you change the airing sign a bit, or keep it as it is in the app ?

**Comment by shashank-lol** [comment]
Ok

**Comment by Abhigyan103** [comment]
Any update ?

**Comment by shashank-lol** [comment]
Will be done by tomorrow
