### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/AniAirs#6]
Add a `README` for this repository explaining the technologies used.

**Comment by Redvey** [comment]
Hello there, I hope to help with this issue too.

**Comment by sajid-31** [comment]
Can you Assign this issue to me under JWOC?

**Comment by Abhigyan103** [comment]
Is there any update ?

**Comment by sajid-31** [comment]
What all sub-headings should I include?
About The Project,  Features, Tech Stack, Demo, Getting Started, Contributing, License, Contributors
Are these enough?
