### ISSUE TITLE
Add a login page

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/AniAirs#8]
Add a login UI with sign in with Google button (No login logic required).

**Comment by YuvrajSingh3110** [comment]
Hey @Abhigyan103  can you assign this to me I have a sample screen to make signup and login screens. I would me making some changes to this ui to make it more themed to anime. 

![Peloton Android 223](https://github.com/Abhigyan103/AniAirs/assets/96365625/5d1ce221-a951-4a84-a44d-0dd4ceed35ff)

**Comment by Redvey** [comment]
Hello @Abhigyan103 , please assign this to me.
